algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2023
// Seção de Declarações 
var
salario : inteiro
reajuste_porcentagem : inteiro
novo_salario : real
inicio
escreva("Salário:")
leia(salario)
escreva("Porcentagem de reajuste:")
leia(reajuste_porcentagem)
novo_salario :=salario*reajuste_porcentagem/100
escreva("Novo_salário =", novo_salario+salario)





// Seção de Comandos 
fimalgoritmo
