algoritmo "semnome"
// Função :
// Autor :
// Data : 13/03/2023
// Seção de Declarações 
var
n1 : real
n2 : real
n3 : real
mediafinal : real
soma : real
inicio
escreval("Nota 1:")
leia(n1)
escreval("Nota 2:")
leia(n2)
escreval("Nota3:")
leia(n3)
soma :=(2+3+5)
mediafinal := ((n1*2)+(n2*3)+(n3*5))/soma
escreva("Média Final:", mediafinal:5:2)

// Seção de Comandos 
fimalgoritmo
